### PR TITLE
Prevent duplicate selectors being added to reset ruleset

### PR DESCRIPTION
**Pull request by simonsmith**
If a selector appeared more than once (media query, nesting) it was being duplicated in the reset ruleset. This change adds a check for the selector first. 

cc @giuseppeg

### CODE REVIEW

**Comment by giuseppeg** [comment]
Since we are in ES6 I would use a `Set` instead of an `Array` – access with `has` is `O(1)` and you won't need the extra `contains` helper

**Comment by simonsmith** [comment]
That's a good shout but I'd need to add the babel polyfill and I wonder if it's worth the extra code.

**Comment by giuseppeg** [comment]
@simonsmith ok, your call! the changes looks good to me

**Comment by maximkoretskiy** [comment]
@simonsmith Could you add changes description into unrealesed section of changelog

**Comment by simonsmith** [comment]
@maximkoretskiy Done

**Comment by simonsmith** [comment]
I'll just rebase this with your latest changes

**Comment by maximkoretskiy** [comment]
@simonsmith sorry. Just pushed fix. could you resolve the conflict?

**Comment by maximkoretskiy** [comment]
Just published your changes to npm. Thank U guys!

**Pull request merged**
