### PR TITLE
Move the selector matcher to OnceExit

### LINKED ISSUE #32: Not working with latest (5.0.3) version of postcss-nested
See https://github.com/postcss/postcss-nested/issues/113

@maximkoretskiy do you have any thoughts on this before I work on it some more?

### PR DESCRIPTION
**Pull request by justafish**
Fixes #32

### CODE REVIEW

**Comment by maximkoretskiy** [comment]
Could you please add some regression test? This change does not make sense without outer reasoning

**Comment by maximkoretskiy** [comment]
@justafish ping

**Comment by justafish** [comment]
@maximkoretskiy test added and cherry picked to a draft PR so you can see the failure in the CI #36

**Comment by justafish** [comment]
@maximkoretskiy is there anything else you need here?

**Comment by maximkoretskiy** [comment]
Thanks! Now all good. Will publish soon

**Comment by maximkoretskiy** [comment]
Done

**Pull request merged**
